&IF DEFINED(DATATYPE_FUNCTION) = 0 &THEN
    &GLOBAL-DEFINE DATATYPE_FUNCTION
    &GLOBAL-DEFINE DEFAULT-FRAME ASDF_ASDF

    FUNCTION getDataType RETURNS CHARACTER (INPUT hip_handle AS HANDLE) FORWARD.

    FUNCTION getDataType RETURNS CHARACTER (INPUT hip_handle AS HANDLE):
        RETURN hip_handle:DATA-TYPE.
    END FUNCTION.
&ENDIF