&IF DEFINED(FILEOBJ_REF) > 0 &THEN
    &SCOPED-DEFINE FILEOBJ_TYPE REFERENCE-ONLY
&ENDIF

DEFINE TEMP-TABLE tempFile {&FILEOBJ_TYPE}
    FIELD i_idx  AS INTEGER
    FIELD c_file AS CHARACTER
    FIELD l_read AS LOGICAL.

DEFINE TEMP-TABLE fileRec {&FILEOBJ_TYPE}
    FIELD i_parent AS INTEGER
    FIELD i_idx    AS INTEGER
    FIELD c_value  AS CHARACTER.
