{datatype.i}

&IF DEFINED(DEFAULT_FRAME) = 0 &THEN
    &GLOBAL-DEFINE DEFAULT_FRAME ASDF_ASDF
&ENDIF

DEFINE FRAME {&DEFAULT_FRAME}
    {1}.

ASSIGN {2} = getDataType({1}:HANDLE IN FRAME {&DEFAULT_FRAME}) NO-ERROR.